export const names = [
	"Doctor Foreman",
	"Merlin",
	"The Destroyer of Worlds",
	"John Smith",
	"Sweetie",
	"Theta Sigma",
	"Master",
	"Maximus Pettulian",
	"Zeus",
	"Doctor Caligari",
	"Traveller from Beyond Time",
	"Doctor Who",
	"Oncoming Storm",
	"Pops",
	"Mister Pastry",
	"Mary Berry",
	"Corporal Jones",
	"Examiner",
	"Doctor Galloway",
	"Clown",
	"Scarecrow",
	"Quiquaequod",
	"Dandy",
	"Prisoner 177781",
	"Fancy Pants",
	"Heironymous",
	"Evil One",
	"Xoanon",
	"?",
	"Demon",
	"Old One",
	"Professor",
	"John Doe",
	"Destroyer of Skaro",
	"Doctor Bowman",
	"Predator",
	"Predator of the Daleks",
	"Warrior",
	"Mad Fool",
	"Grandad",
	"Captain Grumpy",
	"Doctor of War",
	"Butcher of Skull Moon",
	"Mr Spock",
	"U-Boat Captain",
	"Big Ears",
	"Great Exterminator",
	"Great Destroyer",
	"Heathen",
	"Doctor James McCrimmon",
	"Sir Doctor of TARDIS",
	"Martian",
	"Gramps",
	"Gandalf",
	"Spartacus",
	"Spaceman",
	"Doctor Noble",
	"Mr Conditional Clause",
	"Chief Inspector Smith",
	"Pretty Boy",
	"Dark Lord",
	"Time Lord Victorious",
	"Bringer of Darkness",
	"Matchstick Man",
	"Sandshoes",
	"Dick van Dyke",
	"Hero",
	"Number Ten",
	"Raggedy Man",
	"Madman with a Box",
	"Ancient Amateur",
	"Rotmeister",
	"Captain Troy Handsome of International Rescue",
	"Caesar",
	"My Love",
	"King of Okay",
	"Thief",
	"Beautiful Idiot",
	"Time Boy",
	"Also Not Mum",
	"Caretaker",
	"The Chin",
	"Sherlock Holmes",
	"Mad Monk",
	"Monster",
	"Proconsul",
	"Clara's Boyfriend",
	"Chinny",
	"Number Eleven",
	"Number Twelve",
	"Imp of the Pandorica",
	"Beast of Trenzalore",
	"Boney Rascal",
	"Stranger",
	"Architect",
	"Space Dad",
	"Skovox Artificer",
	"Mr President",
	"President of the World",
	"Skeleton Man",
	"Magician",
	"The Eyebrows",
	"Odin",
	"Doctor John Disco",
	"Doctor Funkenstein",
	"Basil",
	"Hybrid",
	"Doctor Mysterio",
	"Special Agent Dan Dangerous",
	"Timeless Child",
	"Doc",
	"Witchfinder General",
	"Witchfinder Assistant",
	"Marvellous Apparating Lady",
	"Mrs Doctor",
	"Fugitive",
	"Valeyard",
	"Vessel of the Final Darkness",
	"Curator",
	"Damsel",
	"Shadow of the Valeyard",
	"Last Tree of Garsennon",
	"Ruth Clayton",
	"Brendan",
	"Doctor Disco",
	"The Sandman",
];

export const propics = [
	"DOCTORS/01",
	"DOCTORS/02",
	"DOCTORS/03",
	"DOCTORS/04",
	"DOCTORS/05",
	"DOCTORS/06",
	"DOCTORS/07",
	"DOCTORS/08",
	"DOCTORS/09",
	"DOCTORS/10",
	"DOCTORS/11",
	"DOCTORS/12",
	"DOCTORS/13",
	"DOCTORS/WAR",
	"DOCTORS/FUGITIVE",
];
